
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'HomeAboutSection': typeof import("../components/Home/AboutSection.vue")['default']
    'HomeBannerSection': typeof import("../components/Home/BannerSection.vue")['default']
    'HomeHeaderSliderSection': typeof import("../components/Home/HeaderSliderSection.vue")['default']
    'HomePortfolioSection': typeof import("../components/Home/PortfolioSection.vue")['default']
    'HomeTestmonialsSection': typeof import("../components/Home/TestmonialsSection.vue")['default']
    'LayoutsMainFooter': typeof import("../components/layouts/MainFooter.vue")['default']
    'SharedBadge': typeof import("../components/shared/Badge.vue")['default']
    'SharedBoldTitle': typeof import("../components/shared/BoldTitle.vue")['default']
    'SharedHeaderBreadCrumb': typeof import("../components/shared/HeaderBreadCrumb.vue")['default']
    'SharedProductSwiper': typeof import("../components/shared/ProductSwiper.vue")['default']
    'SharedSectionHeader': typeof import("../components/shared/SectionHeader.vue")['default']
    'SharedSubTitle': typeof import("../components/shared/SubTitle.vue")['default']
    'SharedTitle': typeof import("../components/shared/Title.vue")['default']
    'SharedTitleHeaderSection': typeof import("../components/shared/TitleHeaderSection.vue")['default']
    'SharedButtonsPrimaryButton': typeof import("../components/shared/buttons/PrimaryButton.vue")['default']
    'SharedCardsProductCard': typeof import("../components/shared/cards/ProductCard.vue")['default']
    'SharedFormCountryCode': typeof import("../components/shared/form/CountryCode.vue")['default']
    'SharedFormInputField': typeof import("../components/shared/form/InputField.vue")['default']
    'SharedFormInputLabel': typeof import("../components/shared/form/InputLabel.vue")['default']
    'SharedFormLabelField': typeof import("../components/shared/form/LabelField.vue")['default']
    'SharedFormMainSelect': typeof import("../components/shared/form/MainSelect.vue")['default']
    'SharedFormPhoneInputField': typeof import("../components/shared/form/PhoneInputField.vue")['default']
    'SharedFormUploadFile': typeof import("../components/shared/form/UploadFile.vue")['default']
    'SharedLodersLoaderButton': typeof import("../components/shared/loders/LoaderButton.vue")['default']
    'SharedLodersLoading': typeof import("../components/shared/loders/Loading.vue")['default']
    'SharedLodersLoadingPage': typeof import("../components/shared/loders/LoadingPage.vue")['default']
    'SharedLodersSpinner': typeof import("../components/shared/loders/Spinner.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Icon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'IconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'Swiper': typeof import("swiper/vue")['Swiper']
    'SwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'NuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'AutoComplete': typeof import("primevue/autocomplete")['default']
    'Calendar': typeof import("primevue/calendar")['default']
    'CascadeSelect': typeof import("primevue/cascadeselect")['default']
    'Checkbox': typeof import("primevue/checkbox")['default']
    'Chips': typeof import("primevue/chips")['default']
    'ColorPicker': typeof import("primevue/colorpicker")['default']
    'Dropdown': typeof import("primevue/dropdown")['default']
    'InputGroup': typeof import("primevue/inputgroup")['default']
    'InputGroupAddon': typeof import("primevue/inputgroupaddon")['default']
    'InputMask': typeof import("primevue/inputmask")['default']
    'InputNumber': typeof import("primevue/inputnumber")['default']
    'InputSwitch': typeof import("primevue/inputswitch")['default']
    'InputText': typeof import("primevue/inputtext")['default']
    'Knob': typeof import("primevue/knob")['default']
    'Listbox': typeof import("primevue/listbox")['default']
    'MultiSelect': typeof import("primevue/multiselect")['default']
    'Password': typeof import("primevue/password")['default']
    'RadioButton': typeof import("primevue/radiobutton")['default']
    'Rating': typeof import("primevue/rating")['default']
    'SelectButton': typeof import("primevue/selectbutton")['default']
    'Slider': typeof import("primevue/slider")['default']
    'Textarea': typeof import("primevue/textarea")['default']
    'ToggleButton': typeof import("primevue/togglebutton")['default']
    'TreeSelect': typeof import("primevue/treeselect")['default']
    'TriStateCheckbox': typeof import("primevue/tristatecheckbox")['default']
    'Button': typeof import("primevue/button")['default']
    'SpeedDial': typeof import("primevue/speeddial")['default']
    'SplitButton': typeof import("primevue/splitbutton")['default']
    'Column': typeof import("primevue/column")['default']
    'Row': typeof import("primevue/row")['default']
    'ColumnGroup': typeof import("primevue/columngroup")['default']
    'DataTable': typeof import("primevue/datatable")['default']
    'DataView': typeof import("primevue/dataview")['default']
    'DataViewLayoutOptions': typeof import("primevue/dataviewlayoutoptions")['default']
    'OrderList': typeof import("primevue/orderlist")['default']
    'OrganizationChart': typeof import("primevue/organizationchart")['default']
    'Paginator': typeof import("primevue/paginator")['default']
    'PickList': typeof import("primevue/picklist")['default']
    'Tree': typeof import("primevue/tree")['default']
    'TreeTable': typeof import("primevue/treetable")['default']
    'Timeline': typeof import("primevue/timeline")['default']
    'VirtualScroller': typeof import("primevue/virtualscroller")['default']
    'Accordion': typeof import("primevue/accordion")['default']
    'AccordionTab': typeof import("primevue/accordiontab")['default']
    'Card': typeof import("primevue/card")['default']
    'DeferredContent': typeof import("primevue/deferredcontent")['default']
    'Divider': typeof import("primevue/divider")['default']
    'Fieldset': typeof import("primevue/fieldset")['default']
    'Panel': typeof import("primevue/panel")['default']
    'ScrollPanel': typeof import("primevue/scrollpanel")['default']
    'Splitter': typeof import("primevue/splitter")['default']
    'SplitterPanel': typeof import("primevue/splitterpanel")['default']
    'TabView': typeof import("primevue/tabview")['default']
    'TabPanel': typeof import("primevue/tabpanel")['default']
    'Toolbar': typeof import("primevue/toolbar")['default']
    'ConfirmDialog': typeof import("primevue/confirmdialog")['default']
    'ConfirmPopup': typeof import("primevue/confirmpopup")['default']
    'Dialog': typeof import("primevue/dialog")['default']
    'DynamicDialog': typeof import("primevue/dynamicdialog")['default']
    'OverlayPanel': typeof import("primevue/overlaypanel")['default']
    'Sidebar': typeof import("primevue/sidebar")['default']
    'FileUpload': typeof import("primevue/fileupload")['default']
    'Breadcrumb': typeof import("primevue/breadcrumb")['default']
    'ContextMenu': typeof import("primevue/contextmenu")['default']
    'Dock': typeof import("primevue/dock")['default']
    'Menu': typeof import("primevue/menu")['default']
    'Menubar': typeof import("primevue/menubar")['default']
    'MegaMenu': typeof import("primevue/megamenu")['default']
    'PanelMenu': typeof import("primevue/panelmenu")['default']
    'Steps': typeof import("primevue/steps")['default']
    'TabMenu': typeof import("primevue/tabmenu")['default']
    'TieredMenu': typeof import("primevue/tieredmenu")['default']
    'Message': typeof import("primevue/message")['default']
    'InlineMessage': typeof import("primevue/inlinemessage")['default']
    'Toast': typeof import("primevue/toast")['default']
    'Carousel': typeof import("primevue/carousel")['default']
    'Galleria': typeof import("primevue/galleria")['default']
    'Image': typeof import("primevue/image")['default']
    'Avatar': typeof import("primevue/avatar")['default']
    'AvatarGroup': typeof import("primevue/avatargroup")['default']
    'Badge': typeof import("primevue/badge")['default']
    'BlockUI': typeof import("primevue/blockui")['default']
    'Chip': typeof import("primevue/chip")['default']
    'Inplace': typeof import("primevue/inplace")['default']
    'ScrollTop': typeof import("primevue/scrolltop")['default']
    'Skeleton': typeof import("primevue/skeleton")['default']
    'ProgressBar': typeof import("primevue/progressbar")['default']
    'ProgressSpinner': typeof import("primevue/progressspinner")['default']
    'Tag': typeof import("primevue/tag")['default']
    'Terminal': typeof import("primevue/terminal")['default']
    'Field': typeof import("vee-validate")['Field']
    'ValidationForm': typeof import("vee-validate")['Form']
    'ErrorMessage': typeof import("vee-validate")['ErrorMessage']
    'VeeFieldArray': typeof import("vee-validate")['FieldArray']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyHomeAboutSection': typeof import("../components/Home/AboutSection.vue")['default']
    'LazyHomeBannerSection': typeof import("../components/Home/BannerSection.vue")['default']
    'LazyHomeHeaderSliderSection': typeof import("../components/Home/HeaderSliderSection.vue")['default']
    'LazyHomePortfolioSection': typeof import("../components/Home/PortfolioSection.vue")['default']
    'LazyHomeTestmonialsSection': typeof import("../components/Home/TestmonialsSection.vue")['default']
    'LazyLayoutsMainFooter': typeof import("../components/layouts/MainFooter.vue")['default']
    'LazySharedBadge': typeof import("../components/shared/Badge.vue")['default']
    'LazySharedBoldTitle': typeof import("../components/shared/BoldTitle.vue")['default']
    'LazySharedHeaderBreadCrumb': typeof import("../components/shared/HeaderBreadCrumb.vue")['default']
    'LazySharedProductSwiper': typeof import("../components/shared/ProductSwiper.vue")['default']
    'LazySharedSectionHeader': typeof import("../components/shared/SectionHeader.vue")['default']
    'LazySharedSubTitle': typeof import("../components/shared/SubTitle.vue")['default']
    'LazySharedTitle': typeof import("../components/shared/Title.vue")['default']
    'LazySharedTitleHeaderSection': typeof import("../components/shared/TitleHeaderSection.vue")['default']
    'LazySharedButtonsPrimaryButton': typeof import("../components/shared/buttons/PrimaryButton.vue")['default']
    'LazySharedCardsProductCard': typeof import("../components/shared/cards/ProductCard.vue")['default']
    'LazySharedFormCountryCode': typeof import("../components/shared/form/CountryCode.vue")['default']
    'LazySharedFormInputField': typeof import("../components/shared/form/InputField.vue")['default']
    'LazySharedFormInputLabel': typeof import("../components/shared/form/InputLabel.vue")['default']
    'LazySharedFormLabelField': typeof import("../components/shared/form/LabelField.vue")['default']
    'LazySharedFormMainSelect': typeof import("../components/shared/form/MainSelect.vue")['default']
    'LazySharedFormPhoneInputField': typeof import("../components/shared/form/PhoneInputField.vue")['default']
    'LazySharedFormUploadFile': typeof import("../components/shared/form/UploadFile.vue")['default']
    'LazySharedLodersLoaderButton': typeof import("../components/shared/loders/LoaderButton.vue")['default']
    'LazySharedLodersLoading': typeof import("../components/shared/loders/Loading.vue")['default']
    'LazySharedLodersLoadingPage': typeof import("../components/shared/loders/LoadingPage.vue")['default']
    'LazySharedLodersSpinner': typeof import("../components/shared/loders/Spinner.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyIcon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'LazyIconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'LazySwiper': typeof import("swiper/vue")['Swiper']
    'LazySwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'LazyNuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazyAutoComplete': typeof import("primevue/autocomplete")['default']
    'LazyCalendar': typeof import("primevue/calendar")['default']
    'LazyCascadeSelect': typeof import("primevue/cascadeselect")['default']
    'LazyCheckbox': typeof import("primevue/checkbox")['default']
    'LazyChips': typeof import("primevue/chips")['default']
    'LazyColorPicker': typeof import("primevue/colorpicker")['default']
    'LazyDropdown': typeof import("primevue/dropdown")['default']
    'LazyInputGroup': typeof import("primevue/inputgroup")['default']
    'LazyInputGroupAddon': typeof import("primevue/inputgroupaddon")['default']
    'LazyInputMask': typeof import("primevue/inputmask")['default']
    'LazyInputNumber': typeof import("primevue/inputnumber")['default']
    'LazyInputSwitch': typeof import("primevue/inputswitch")['default']
    'LazyInputText': typeof import("primevue/inputtext")['default']
    'LazyKnob': typeof import("primevue/knob")['default']
    'LazyListbox': typeof import("primevue/listbox")['default']
    'LazyMultiSelect': typeof import("primevue/multiselect")['default']
    'LazyPassword': typeof import("primevue/password")['default']
    'LazyRadioButton': typeof import("primevue/radiobutton")['default']
    'LazyRating': typeof import("primevue/rating")['default']
    'LazySelectButton': typeof import("primevue/selectbutton")['default']
    'LazySlider': typeof import("primevue/slider")['default']
    'LazyTextarea': typeof import("primevue/textarea")['default']
    'LazyToggleButton': typeof import("primevue/togglebutton")['default']
    'LazyTreeSelect': typeof import("primevue/treeselect")['default']
    'LazyTriStateCheckbox': typeof import("primevue/tristatecheckbox")['default']
    'LazyButton': typeof import("primevue/button")['default']
    'LazySpeedDial': typeof import("primevue/speeddial")['default']
    'LazySplitButton': typeof import("primevue/splitbutton")['default']
    'LazyColumn': typeof import("primevue/column")['default']
    'LazyRow': typeof import("primevue/row")['default']
    'LazyColumnGroup': typeof import("primevue/columngroup")['default']
    'LazyDataTable': typeof import("primevue/datatable")['default']
    'LazyDataView': typeof import("primevue/dataview")['default']
    'LazyDataViewLayoutOptions': typeof import("primevue/dataviewlayoutoptions")['default']
    'LazyOrderList': typeof import("primevue/orderlist")['default']
    'LazyOrganizationChart': typeof import("primevue/organizationchart")['default']
    'LazyPaginator': typeof import("primevue/paginator")['default']
    'LazyPickList': typeof import("primevue/picklist")['default']
    'LazyTree': typeof import("primevue/tree")['default']
    'LazyTreeTable': typeof import("primevue/treetable")['default']
    'LazyTimeline': typeof import("primevue/timeline")['default']
    'LazyVirtualScroller': typeof import("primevue/virtualscroller")['default']
    'LazyAccordion': typeof import("primevue/accordion")['default']
    'LazyAccordionTab': typeof import("primevue/accordiontab")['default']
    'LazyCard': typeof import("primevue/card")['default']
    'LazyDeferredContent': typeof import("primevue/deferredcontent")['default']
    'LazyDivider': typeof import("primevue/divider")['default']
    'LazyFieldset': typeof import("primevue/fieldset")['default']
    'LazyPanel': typeof import("primevue/panel")['default']
    'LazyScrollPanel': typeof import("primevue/scrollpanel")['default']
    'LazySplitter': typeof import("primevue/splitter")['default']
    'LazySplitterPanel': typeof import("primevue/splitterpanel")['default']
    'LazyTabView': typeof import("primevue/tabview")['default']
    'LazyTabPanel': typeof import("primevue/tabpanel")['default']
    'LazyToolbar': typeof import("primevue/toolbar")['default']
    'LazyConfirmDialog': typeof import("primevue/confirmdialog")['default']
    'LazyConfirmPopup': typeof import("primevue/confirmpopup")['default']
    'LazyDialog': typeof import("primevue/dialog")['default']
    'LazyDynamicDialog': typeof import("primevue/dynamicdialog")['default']
    'LazyOverlayPanel': typeof import("primevue/overlaypanel")['default']
    'LazySidebar': typeof import("primevue/sidebar")['default']
    'LazyFileUpload': typeof import("primevue/fileupload")['default']
    'LazyBreadcrumb': typeof import("primevue/breadcrumb")['default']
    'LazyContextMenu': typeof import("primevue/contextmenu")['default']
    'LazyDock': typeof import("primevue/dock")['default']
    'LazyMenu': typeof import("primevue/menu")['default']
    'LazyMenubar': typeof import("primevue/menubar")['default']
    'LazyMegaMenu': typeof import("primevue/megamenu")['default']
    'LazyPanelMenu': typeof import("primevue/panelmenu")['default']
    'LazySteps': typeof import("primevue/steps")['default']
    'LazyTabMenu': typeof import("primevue/tabmenu")['default']
    'LazyTieredMenu': typeof import("primevue/tieredmenu")['default']
    'LazyMessage': typeof import("primevue/message")['default']
    'LazyInlineMessage': typeof import("primevue/inlinemessage")['default']
    'LazyToast': typeof import("primevue/toast")['default']
    'LazyCarousel': typeof import("primevue/carousel")['default']
    'LazyGalleria': typeof import("primevue/galleria")['default']
    'LazyImage': typeof import("primevue/image")['default']
    'LazyAvatar': typeof import("primevue/avatar")['default']
    'LazyAvatarGroup': typeof import("primevue/avatargroup")['default']
    'LazyBadge': typeof import("primevue/badge")['default']
    'LazyBlockUI': typeof import("primevue/blockui")['default']
    'LazyChip': typeof import("primevue/chip")['default']
    'LazyInplace': typeof import("primevue/inplace")['default']
    'LazyScrollTop': typeof import("primevue/scrolltop")['default']
    'LazySkeleton': typeof import("primevue/skeleton")['default']
    'LazyProgressBar': typeof import("primevue/progressbar")['default']
    'LazyProgressSpinner': typeof import("primevue/progressspinner")['default']
    'LazyTag': typeof import("primevue/tag")['default']
    'LazyTerminal': typeof import("primevue/terminal")['default']
    'LazyField': typeof import("vee-validate")['Field']
    'LazyValidationForm': typeof import("vee-validate")['Form']
    'LazyErrorMessage': typeof import("vee-validate")['ErrorMessage']
    'LazyVeeFieldArray': typeof import("vee-validate")['FieldArray']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const HomeAboutSection: typeof import("../components/Home/AboutSection.vue")['default']
export const HomeBannerSection: typeof import("../components/Home/BannerSection.vue")['default']
export const HomeHeaderSliderSection: typeof import("../components/Home/HeaderSliderSection.vue")['default']
export const HomePortfolioSection: typeof import("../components/Home/PortfolioSection.vue")['default']
export const HomeTestmonialsSection: typeof import("../components/Home/TestmonialsSection.vue")['default']
export const LayoutsMainFooter: typeof import("../components/layouts/MainFooter.vue")['default']
export const SharedBadge: typeof import("../components/shared/Badge.vue")['default']
export const SharedBoldTitle: typeof import("../components/shared/BoldTitle.vue")['default']
export const SharedHeaderBreadCrumb: typeof import("../components/shared/HeaderBreadCrumb.vue")['default']
export const SharedProductSwiper: typeof import("../components/shared/ProductSwiper.vue")['default']
export const SharedSectionHeader: typeof import("../components/shared/SectionHeader.vue")['default']
export const SharedSubTitle: typeof import("../components/shared/SubTitle.vue")['default']
export const SharedTitle: typeof import("../components/shared/Title.vue")['default']
export const SharedTitleHeaderSection: typeof import("../components/shared/TitleHeaderSection.vue")['default']
export const SharedButtonsPrimaryButton: typeof import("../components/shared/buttons/PrimaryButton.vue")['default']
export const SharedCardsProductCard: typeof import("../components/shared/cards/ProductCard.vue")['default']
export const SharedFormCountryCode: typeof import("../components/shared/form/CountryCode.vue")['default']
export const SharedFormInputField: typeof import("../components/shared/form/InputField.vue")['default']
export const SharedFormInputLabel: typeof import("../components/shared/form/InputLabel.vue")['default']
export const SharedFormLabelField: typeof import("../components/shared/form/LabelField.vue")['default']
export const SharedFormMainSelect: typeof import("../components/shared/form/MainSelect.vue")['default']
export const SharedFormPhoneInputField: typeof import("../components/shared/form/PhoneInputField.vue")['default']
export const SharedFormUploadFile: typeof import("../components/shared/form/UploadFile.vue")['default']
export const SharedLodersLoaderButton: typeof import("../components/shared/loders/LoaderButton.vue")['default']
export const SharedLodersLoading: typeof import("../components/shared/loders/Loading.vue")['default']
export const SharedLodersLoadingPage: typeof import("../components/shared/loders/LoadingPage.vue")['default']
export const SharedLodersSpinner: typeof import("../components/shared/loders/Spinner.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Icon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const IconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const Swiper: typeof import("swiper/vue")['Swiper']
export const SwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const AutoComplete: typeof import("primevue/autocomplete")['default']
export const Calendar: typeof import("primevue/calendar")['default']
export const CascadeSelect: typeof import("primevue/cascadeselect")['default']
export const Checkbox: typeof import("primevue/checkbox")['default']
export const Chips: typeof import("primevue/chips")['default']
export const ColorPicker: typeof import("primevue/colorpicker")['default']
export const Dropdown: typeof import("primevue/dropdown")['default']
export const InputGroup: typeof import("primevue/inputgroup")['default']
export const InputGroupAddon: typeof import("primevue/inputgroupaddon")['default']
export const InputMask: typeof import("primevue/inputmask")['default']
export const InputNumber: typeof import("primevue/inputnumber")['default']
export const InputSwitch: typeof import("primevue/inputswitch")['default']
export const InputText: typeof import("primevue/inputtext")['default']
export const Knob: typeof import("primevue/knob")['default']
export const Listbox: typeof import("primevue/listbox")['default']
export const MultiSelect: typeof import("primevue/multiselect")['default']
export const Password: typeof import("primevue/password")['default']
export const RadioButton: typeof import("primevue/radiobutton")['default']
export const Rating: typeof import("primevue/rating")['default']
export const SelectButton: typeof import("primevue/selectbutton")['default']
export const Slider: typeof import("primevue/slider")['default']
export const Textarea: typeof import("primevue/textarea")['default']
export const ToggleButton: typeof import("primevue/togglebutton")['default']
export const TreeSelect: typeof import("primevue/treeselect")['default']
export const TriStateCheckbox: typeof import("primevue/tristatecheckbox")['default']
export const Button: typeof import("primevue/button")['default']
export const SpeedDial: typeof import("primevue/speeddial")['default']
export const SplitButton: typeof import("primevue/splitbutton")['default']
export const Column: typeof import("primevue/column")['default']
export const Row: typeof import("primevue/row")['default']
export const ColumnGroup: typeof import("primevue/columngroup")['default']
export const DataTable: typeof import("primevue/datatable")['default']
export const DataView: typeof import("primevue/dataview")['default']
export const DataViewLayoutOptions: typeof import("primevue/dataviewlayoutoptions")['default']
export const OrderList: typeof import("primevue/orderlist")['default']
export const OrganizationChart: typeof import("primevue/organizationchart")['default']
export const Paginator: typeof import("primevue/paginator")['default']
export const PickList: typeof import("primevue/picklist")['default']
export const Tree: typeof import("primevue/tree")['default']
export const TreeTable: typeof import("primevue/treetable")['default']
export const Timeline: typeof import("primevue/timeline")['default']
export const VirtualScroller: typeof import("primevue/virtualscroller")['default']
export const Accordion: typeof import("primevue/accordion")['default']
export const AccordionTab: typeof import("primevue/accordiontab")['default']
export const Card: typeof import("primevue/card")['default']
export const DeferredContent: typeof import("primevue/deferredcontent")['default']
export const Divider: typeof import("primevue/divider")['default']
export const Fieldset: typeof import("primevue/fieldset")['default']
export const Panel: typeof import("primevue/panel")['default']
export const ScrollPanel: typeof import("primevue/scrollpanel")['default']
export const Splitter: typeof import("primevue/splitter")['default']
export const SplitterPanel: typeof import("primevue/splitterpanel")['default']
export const TabView: typeof import("primevue/tabview")['default']
export const TabPanel: typeof import("primevue/tabpanel")['default']
export const Toolbar: typeof import("primevue/toolbar")['default']
export const ConfirmDialog: typeof import("primevue/confirmdialog")['default']
export const ConfirmPopup: typeof import("primevue/confirmpopup")['default']
export const Dialog: typeof import("primevue/dialog")['default']
export const DynamicDialog: typeof import("primevue/dynamicdialog")['default']
export const OverlayPanel: typeof import("primevue/overlaypanel")['default']
export const Sidebar: typeof import("primevue/sidebar")['default']
export const FileUpload: typeof import("primevue/fileupload")['default']
export const Breadcrumb: typeof import("primevue/breadcrumb")['default']
export const ContextMenu: typeof import("primevue/contextmenu")['default']
export const Dock: typeof import("primevue/dock")['default']
export const Menu: typeof import("primevue/menu")['default']
export const Menubar: typeof import("primevue/menubar")['default']
export const MegaMenu: typeof import("primevue/megamenu")['default']
export const PanelMenu: typeof import("primevue/panelmenu")['default']
export const Steps: typeof import("primevue/steps")['default']
export const TabMenu: typeof import("primevue/tabmenu")['default']
export const TieredMenu: typeof import("primevue/tieredmenu")['default']
export const Message: typeof import("primevue/message")['default']
export const InlineMessage: typeof import("primevue/inlinemessage")['default']
export const Toast: typeof import("primevue/toast")['default']
export const Carousel: typeof import("primevue/carousel")['default']
export const Galleria: typeof import("primevue/galleria")['default']
export const Image: typeof import("primevue/image")['default']
export const Avatar: typeof import("primevue/avatar")['default']
export const AvatarGroup: typeof import("primevue/avatargroup")['default']
export const Badge: typeof import("primevue/badge")['default']
export const BlockUI: typeof import("primevue/blockui")['default']
export const Chip: typeof import("primevue/chip")['default']
export const Inplace: typeof import("primevue/inplace")['default']
export const ScrollTop: typeof import("primevue/scrolltop")['default']
export const Skeleton: typeof import("primevue/skeleton")['default']
export const ProgressBar: typeof import("primevue/progressbar")['default']
export const ProgressSpinner: typeof import("primevue/progressspinner")['default']
export const Tag: typeof import("primevue/tag")['default']
export const Terminal: typeof import("primevue/terminal")['default']
export const Field: typeof import("vee-validate")['Field']
export const ValidationForm: typeof import("vee-validate")['Form']
export const ErrorMessage: typeof import("vee-validate")['ErrorMessage']
export const VeeFieldArray: typeof import("vee-validate")['FieldArray']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyHomeAboutSection: typeof import("../components/Home/AboutSection.vue")['default']
export const LazyHomeBannerSection: typeof import("../components/Home/BannerSection.vue")['default']
export const LazyHomeHeaderSliderSection: typeof import("../components/Home/HeaderSliderSection.vue")['default']
export const LazyHomePortfolioSection: typeof import("../components/Home/PortfolioSection.vue")['default']
export const LazyHomeTestmonialsSection: typeof import("../components/Home/TestmonialsSection.vue")['default']
export const LazyLayoutsMainFooter: typeof import("../components/layouts/MainFooter.vue")['default']
export const LazySharedBadge: typeof import("../components/shared/Badge.vue")['default']
export const LazySharedBoldTitle: typeof import("../components/shared/BoldTitle.vue")['default']
export const LazySharedHeaderBreadCrumb: typeof import("../components/shared/HeaderBreadCrumb.vue")['default']
export const LazySharedProductSwiper: typeof import("../components/shared/ProductSwiper.vue")['default']
export const LazySharedSectionHeader: typeof import("../components/shared/SectionHeader.vue")['default']
export const LazySharedSubTitle: typeof import("../components/shared/SubTitle.vue")['default']
export const LazySharedTitle: typeof import("../components/shared/Title.vue")['default']
export const LazySharedTitleHeaderSection: typeof import("../components/shared/TitleHeaderSection.vue")['default']
export const LazySharedButtonsPrimaryButton: typeof import("../components/shared/buttons/PrimaryButton.vue")['default']
export const LazySharedCardsProductCard: typeof import("../components/shared/cards/ProductCard.vue")['default']
export const LazySharedFormCountryCode: typeof import("../components/shared/form/CountryCode.vue")['default']
export const LazySharedFormInputField: typeof import("../components/shared/form/InputField.vue")['default']
export const LazySharedFormInputLabel: typeof import("../components/shared/form/InputLabel.vue")['default']
export const LazySharedFormLabelField: typeof import("../components/shared/form/LabelField.vue")['default']
export const LazySharedFormMainSelect: typeof import("../components/shared/form/MainSelect.vue")['default']
export const LazySharedFormPhoneInputField: typeof import("../components/shared/form/PhoneInputField.vue")['default']
export const LazySharedFormUploadFile: typeof import("../components/shared/form/UploadFile.vue")['default']
export const LazySharedLodersLoaderButton: typeof import("../components/shared/loders/LoaderButton.vue")['default']
export const LazySharedLodersLoading: typeof import("../components/shared/loders/Loading.vue")['default']
export const LazySharedLodersLoadingPage: typeof import("../components/shared/loders/LoadingPage.vue")['default']
export const LazySharedLodersSpinner: typeof import("../components/shared/loders/Spinner.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyIcon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const LazyIconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const LazySwiper: typeof import("swiper/vue")['Swiper']
export const LazySwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const LazyNuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazyAutoComplete: typeof import("primevue/autocomplete")['default']
export const LazyCalendar: typeof import("primevue/calendar")['default']
export const LazyCascadeSelect: typeof import("primevue/cascadeselect")['default']
export const LazyCheckbox: typeof import("primevue/checkbox")['default']
export const LazyChips: typeof import("primevue/chips")['default']
export const LazyColorPicker: typeof import("primevue/colorpicker")['default']
export const LazyDropdown: typeof import("primevue/dropdown")['default']
export const LazyInputGroup: typeof import("primevue/inputgroup")['default']
export const LazyInputGroupAddon: typeof import("primevue/inputgroupaddon")['default']
export const LazyInputMask: typeof import("primevue/inputmask")['default']
export const LazyInputNumber: typeof import("primevue/inputnumber")['default']
export const LazyInputSwitch: typeof import("primevue/inputswitch")['default']
export const LazyInputText: typeof import("primevue/inputtext")['default']
export const LazyKnob: typeof import("primevue/knob")['default']
export const LazyListbox: typeof import("primevue/listbox")['default']
export const LazyMultiSelect: typeof import("primevue/multiselect")['default']
export const LazyPassword: typeof import("primevue/password")['default']
export const LazyRadioButton: typeof import("primevue/radiobutton")['default']
export const LazyRating: typeof import("primevue/rating")['default']
export const LazySelectButton: typeof import("primevue/selectbutton")['default']
export const LazySlider: typeof import("primevue/slider")['default']
export const LazyTextarea: typeof import("primevue/textarea")['default']
export const LazyToggleButton: typeof import("primevue/togglebutton")['default']
export const LazyTreeSelect: typeof import("primevue/treeselect")['default']
export const LazyTriStateCheckbox: typeof import("primevue/tristatecheckbox")['default']
export const LazyButton: typeof import("primevue/button")['default']
export const LazySpeedDial: typeof import("primevue/speeddial")['default']
export const LazySplitButton: typeof import("primevue/splitbutton")['default']
export const LazyColumn: typeof import("primevue/column")['default']
export const LazyRow: typeof import("primevue/row")['default']
export const LazyColumnGroup: typeof import("primevue/columngroup")['default']
export const LazyDataTable: typeof import("primevue/datatable")['default']
export const LazyDataView: typeof import("primevue/dataview")['default']
export const LazyDataViewLayoutOptions: typeof import("primevue/dataviewlayoutoptions")['default']
export const LazyOrderList: typeof import("primevue/orderlist")['default']
export const LazyOrganizationChart: typeof import("primevue/organizationchart")['default']
export const LazyPaginator: typeof import("primevue/paginator")['default']
export const LazyPickList: typeof import("primevue/picklist")['default']
export const LazyTree: typeof import("primevue/tree")['default']
export const LazyTreeTable: typeof import("primevue/treetable")['default']
export const LazyTimeline: typeof import("primevue/timeline")['default']
export const LazyVirtualScroller: typeof import("primevue/virtualscroller")['default']
export const LazyAccordion: typeof import("primevue/accordion")['default']
export const LazyAccordionTab: typeof import("primevue/accordiontab")['default']
export const LazyCard: typeof import("primevue/card")['default']
export const LazyDeferredContent: typeof import("primevue/deferredcontent")['default']
export const LazyDivider: typeof import("primevue/divider")['default']
export const LazyFieldset: typeof import("primevue/fieldset")['default']
export const LazyPanel: typeof import("primevue/panel")['default']
export const LazyScrollPanel: typeof import("primevue/scrollpanel")['default']
export const LazySplitter: typeof import("primevue/splitter")['default']
export const LazySplitterPanel: typeof import("primevue/splitterpanel")['default']
export const LazyTabView: typeof import("primevue/tabview")['default']
export const LazyTabPanel: typeof import("primevue/tabpanel")['default']
export const LazyToolbar: typeof import("primevue/toolbar")['default']
export const LazyConfirmDialog: typeof import("primevue/confirmdialog")['default']
export const LazyConfirmPopup: typeof import("primevue/confirmpopup")['default']
export const LazyDialog: typeof import("primevue/dialog")['default']
export const LazyDynamicDialog: typeof import("primevue/dynamicdialog")['default']
export const LazyOverlayPanel: typeof import("primevue/overlaypanel")['default']
export const LazySidebar: typeof import("primevue/sidebar")['default']
export const LazyFileUpload: typeof import("primevue/fileupload")['default']
export const LazyBreadcrumb: typeof import("primevue/breadcrumb")['default']
export const LazyContextMenu: typeof import("primevue/contextmenu")['default']
export const LazyDock: typeof import("primevue/dock")['default']
export const LazyMenu: typeof import("primevue/menu")['default']
export const LazyMenubar: typeof import("primevue/menubar")['default']
export const LazyMegaMenu: typeof import("primevue/megamenu")['default']
export const LazyPanelMenu: typeof import("primevue/panelmenu")['default']
export const LazySteps: typeof import("primevue/steps")['default']
export const LazyTabMenu: typeof import("primevue/tabmenu")['default']
export const LazyTieredMenu: typeof import("primevue/tieredmenu")['default']
export const LazyMessage: typeof import("primevue/message")['default']
export const LazyInlineMessage: typeof import("primevue/inlinemessage")['default']
export const LazyToast: typeof import("primevue/toast")['default']
export const LazyCarousel: typeof import("primevue/carousel")['default']
export const LazyGalleria: typeof import("primevue/galleria")['default']
export const LazyImage: typeof import("primevue/image")['default']
export const LazyAvatar: typeof import("primevue/avatar")['default']
export const LazyAvatarGroup: typeof import("primevue/avatargroup")['default']
export const LazyBadge: typeof import("primevue/badge")['default']
export const LazyBlockUI: typeof import("primevue/blockui")['default']
export const LazyChip: typeof import("primevue/chip")['default']
export const LazyInplace: typeof import("primevue/inplace")['default']
export const LazyScrollTop: typeof import("primevue/scrolltop")['default']
export const LazySkeleton: typeof import("primevue/skeleton")['default']
export const LazyProgressBar: typeof import("primevue/progressbar")['default']
export const LazyProgressSpinner: typeof import("primevue/progressspinner")['default']
export const LazyTag: typeof import("primevue/tag")['default']
export const LazyTerminal: typeof import("primevue/terminal")['default']
export const LazyField: typeof import("vee-validate")['Field']
export const LazyValidationForm: typeof import("vee-validate")['Form']
export const LazyErrorMessage: typeof import("vee-validate")['ErrorMessage']
export const LazyVeeFieldArray: typeof import("vee-validate")['FieldArray']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
